=== Egor-Dubovik/java/PZ_8/out/production/PZ_8/device.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Device">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Component" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="Name" type="xs:string" use="required"/>
            <xs:attribute name="Origin" type="xs:string" use="required"/>
            <xs:attribute name="Price" type="xs:nonNegativeInteger" use="required"/>
            <xs:attribute name="Type">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Peripheral"/>
                  <xs:enumeration value="Non-Peripheral"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="EnergyConsumption" type="xs:nonNegativeInteger" use="required"/>
            <xs:attribute name="Cooler">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Yes"/>
                  <xs:enumeration value="No"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="Group">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="InputOutput"/>
                  <xs:enumeration value="Multimedia"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="Ports" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Critical" type="xs:boolean" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Egor-Dubovik/java/out/production/PZ_8/device/device.xml
<?xml version="1.0" encoding="UTF-8"?>
<Device xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="device.xsd" Critical="true">
    <Component Name="CPU" Origin="USA" Price="15000" Type="Peripheral" EnergyConsumption="95" Cooler="Yes" Group="InputOutput" Ports="USB"/>
    <Component Name="RAM" Origin="Korea" Price="8000" Type="Peripheral" EnergyConsumption="3" Cooler="No" Group="InputOutput" Ports="USB"/>
    <Component Name="Motherboard" Origin="Taiwan" Price="12000" Type="Non-Peripheral" EnergyConsumption="60" Cooler="Yes" Group="InputOutput" Ports="USB, LPT"/>
    <Component Name="Keyboard" Origin="China" Price="1000" Type="Peripheral" EnergyConsumption="1" Cooler="No" Group="InputOutput" Ports="USB"/>
    <Component Name="Mouse" Origin="China" Price="500" Type="Peripheral" EnergyConsumption="1" Cooler="No" Group="InputOutput" Ports="USB"/>
    <Component Name="Speakers" Origin="Taiwan" Price="2000" Type="Non-Peripheral" EnergyConsumption="10" Cooler="No" Group="Multimedia" Ports="USB"/>
    <Component Name="Monitor" Origin="Korea" Price="20000" Type="Non-Peripheral" EnergyConsumption="80" Cooler="No" Group="InputOutput" Ports="COM, USB"/>
</Device>
